name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - deploy

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Render Deploy
        env:
          deploy_back: ${{ secrets.RENDER_DEPLOY_HOOK_BACK }}
          deploy_front: ${{ secrets.RENDER_DEPLOY_HOOK_FRONT }}
        run: |
          echo "Triggering Render Backend"
          curl -X POST "$deploy_back"
          
          echo "Triggering Render Frontend"
          curl -X POST "$deploy_front"